mitelIdAppPlatAXTelephonyServer: 1.3.6.1.4.1.1027.1.6.8
mitelIdAppPlatCXTelephonyServer: 1.3.6.1.4.1.1027.1.6.4
mitelIdAppPlatCXiTelephonyServer: 1.3.6.1.4.1.1027.1.6.5
mitelIdAppPlatLXTelephonyServer: 1.3.6.1.4.1.1027.1.6.2
mitelIdAppPlatLiteTelephonyServer: 1.3.6.1.4.1.1027.1.6.6
mitelIdAppPlatMXTTelephonyServer: 1.3.6.1.4.1.1027.1.6.9
mitelIdAppPlatMXTelephonyServer: 1.3.6.1.4.1.1027.1.6.3
mitelIdAppPlatMXeTelephonyServer: 1.3.6.1.4.1.1027.1.6.7
mitelIdAppPlatManagementApplicationServer: 1.3.6.1.4.1.1027.1.6.1
mitelIdApplicationPlatforms: 1.3.6.1.4.1.1027.1.6
